### PR TITLE
update example to use latest RN version

### PR DESCRIPTION
**Pull request by skv-headless**
I've created new project and put index.js there

### CODE REVIEW

**Comment by shidhincr** [comment]
+1

**Comment by shidhincr** [comment]
@lucholaf  Wondering why this PR is not merged till now

**Comment by skv-headless** [comment]
BTW I decided not to use this package. Flexbox is enough.

**Comment by shidhincr** [comment]
@skv-headless Cool.. thanks man

**Comment by lucholaf** [comment]
done on #25

**Pull request closed without merging**
