### PR TITLE
Update for current react-native compatibility

### PR DESCRIPTION
**Pull request by peterlandry**
I bumped to version 0.4.0, since this will be a backwards incompatible change.

### CODE REVIEW

**Comment by pthrasher** [comment]
It sucks that this is the official NPM package, and it's just plain broken. I'd prefer to consume the NPM package way more than my own fork... but it looks like @lucholaf isn't actively maintaining this repo.

**Comment by lucholaf** [comment]
@peterlandry thanks
@pthrasher updating npm package pretty soon

**Comment by pthrasher** [comment]
@lucholaf My sincerest apologies... I'll now insert my foot into my mouth, and eat my words. :-)

Thanks for getting this merged in. :-)

**Comment by lucholaf** [comment]
@pthrasher 👍  npm updated too

**Pull request merged**
